# Generated by Django 4.0 on 2022-10-09 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='industries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('logo', models.ImageField(default='images/industries/default.jpg', null=True, upload_to='images/industries/')),
                ('registration_date', models.DateField()),
                ('estb_year', models.DateField()),
                ('cii_id', models.IntegerField()),
                ('website', models.URLField()),
                ('contact_num', models.IntegerField(max_length=12, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
                ('state', models.TextField(max_length=200, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('country', models.TextField(max_length=200, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('domain', models.CharField(choices=[('Business', 'Business'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('IT', 'IT'), ('Law', 'Law'), ('Marketing', 'Marketing'), ('Media', 'Media'), ('Science', 'Science'), ('Manufacturing', 'Manufacturing'), ('Teaching', 'Teaching'), ('Other', 'Other')], default='______', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
                ('headline', models.TextField(max_length=200, null=True)),
                ('currently_emp', models.BooleanField(default=True)),
                ('last_educational_degree', models.CharField(choices=[('______', '______'), ('______', '______')], default='______', max_length=20)),
                ('institute', models.TextField(max_length=200, null=True)),
                ('open_for_jobs', models.BooleanField(default=True)),
                ('resume', models.FileField(default='pdf/resume.pdf', null=True, upload_to='pdf/resume/')),
                ('past_experience', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('skills', models.TextField(max_length=500, null=True)),
                ('linkedin_link', models.URLField()),
                ('github', models.URLField(blank=True)),
                ('job_cat', models.CharField(choices=[('______', '______'), ('______', '______')], default='______', max_length=20)),
                ('contact_num', models.IntegerField(null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='openings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('logo', models.ImageField(default='images/openings/default.jpg', null=True, upload_to='images/openings/')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.industries')),
            ],
        ),
    ]
