# Generated by Django 4.0 on 2022-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='contact_num',
            field=models.IntegerField(null=True),
        ),
    ]
