# Generated by Django 4.0 on 2022-10-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_industries_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='estb_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industries',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='industries',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industries',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='currently_emp',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='headline',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='institute',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
