# Generated by Django 4.0.4 on 2022-10-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_industries_estb_year_alter_industries_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('logo', models.ImageField(default='images/institutes/default.jpg', null=True, upload_to='images/institutes/')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('estb_year', models.DateField(blank=True, null=True)),
                ('cii_id', models.IntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_num', models.IntegerField(null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
                ('state', models.TextField(max_length=200, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('country', models.TextField(max_length=200, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('domain', models.CharField(choices=[('Demo0', 'Demo0'), ('Demo1', 'Demo1'), ('Demo2', 'Demo2'), ('Demo3', 'Demo3'), ('Demo4', 'Demo4'), ('Demo5', 'Demo5'), ('Demo6', 'Demo6'), ('Demo7', 'Demo7'), ('Demo8', 'Demo8'), ('Demo9', 'Demo9'), ('Demo10', 'Demo10'), ('Demo11', 'Demo11')], default='______', max_length=20)),
            ],
        ),
    ]
