# Generated by Django 3.2.12 on 2022-10-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_institutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='openings',
        ),
    ]
