# Generated by Django 4.0.4 on 2022-10-31 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_openings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Openings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('logo', models.ImageField(default='images/openings/default.jpg', null=True, upload_to='images/openings/')),
                ('key_skills', models.TextField(max_length=200, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
                ('state', models.TextField(max_length=200, null=True)),
                ('stipend', models.IntegerField(null=True)),
                ('past_experience_required', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.industries')),
            ],
        ),
    ]
