# Generated by Django 4.0 on 2022-11-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_openings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openings',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.industries'),
        ),
        migrations.AlterField(
            model_name='students',
            name='headline',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('openings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.openings')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.students')),
            ],
        ),
    ]
