# Generated by Django 4.0 on 2022-11-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_openings_industry_alter_students_headline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openings',
            name='logo',
        ),
    ]
