# Generated by Django 3.2.12 on 2022-11-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_openings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='state',
            field=models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('', '')], default='______', max_length=20),
        ),
    ]
