# Generated by Django 4.0 on 2022-11-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_industries_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='openings',
            name='apply_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
