# Generated by Django 3.1.7 on 2022-11-09 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20221109_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
