# Generated by Django 4.1.5 on 2023-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_industries_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="stud_data_upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute_name", models.TextField(max_length=200, null=True)),
                (
                    "excel_file",
                    models.FileField(blank=True, upload_to="instittute_excelfile"),
                ),
                ("insertion_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
