# Generated by Django 4.1.5 on 2023-01-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_profile_institute"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.industries",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="institute",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.institutes",
            ),
        ),
    ]
