# Generated by Django 4.1.5 on 2023-01-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_institutes_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openings",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
