# Generated by Django 3.2.12 on 2023-01-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20230128_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='profile',
        ),
    ]
