# Generated by Django 3.2.12 on 2023-01-28 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_remove_application_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institutes'),
        ),
        migrations.AlterField(
            model_name='application',
            name='openings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.openings'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
