# Generated by Django 4.0 on 2023-01-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20230129_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(max_length=200, null=True)),
                ('problem_description', models.TextField(max_length=500, null=True)),
                ('domain', models.CharField(choices=[('Demo1', 'Demo1'), ('Demo2', 'Demo2'), ('Demo3', 'Demo3'), ('Demo4', 'Demo4'), ('Demo5', 'Demo5'), ('Demo6', 'Demo6'), ('Demo7', 'Demo7'), ('Demo8', 'Demo8'), ('Demo9', 'Demo9')], default='______', max_length=20)),
                ('category', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Embedded', 'Embedded'), ('Networking', 'Networking'), ('Web', 'Web'), ('App', 'App'), ('AI', 'AI'), ('ML', 'ML')], default='______', max_length=20)),
                ('consultancy_date', models.DateField(blank=True, null=True)),
                ('apply_by', models.DateField(blank=True, null=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.industries')),
            ],
        ),
    ]
