# Generated by Django 4.0 on 2023-02-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_institute_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute_applied',
            name='opening_id',
        ),
        migrations.AddField(
            model_name='institute_applied',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institute_applied',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='institute_applied',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.industries'),
        ),
        migrations.AddField(
            model_name='institute_applied',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute_applied',
            name='pdf_file',
            field=models.FileField(default='institute_pdf/pdfdemo.pdf', upload_to='institute_pdf'),
        ),
    ]
