# Generated by Django 3.2.12 on 2023-02-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_institute_applied_opening_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_applied',
            name='approved',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institute_applied',
            name='institute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institutes'),
        ),
    ]
