# Generated by Django 3.2.12 on 2023-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20230209_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute_applied',
            name='institute_name',
        ),
        migrations.AddField(
            model_name='institute_applied',
            name='institute_name',
            field=models.ManyToManyField(null=True, to='main.Institutes'),
        ),
    ]
