# Generated by Django 3.2.12 on 2023-02-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20230209_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='consent_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
                ('pdf_file', models.FileField(default='consent_pdf/pdfdemo.pdf', upload_to='consent_pdf')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Openings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.openings')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.industries')),
                ('institute_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institutes')),
            ],
        ),
    ]
