# Generated by Django 3.2.12 on 2023-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_consent_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent_form',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
