# Generated by Django 3.2.12 on 2023-02-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_consent_form_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent_form',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
